### ISSUE TITLE
Fix send race condition in PostProductEvent

### ISSUE THREAD

**Issue by havardf** [metno/go-mms#11] opened 2020-08-27 06:06 UTC
There is some issue in the Nats cloudevent client which causes the Send function to return too early, causing the connection to NATS to close before the message has actually been sent. 

Currently, its solved with sleep hack.

**Comment by johtoblan** [comment] 2020-08-27 07:15
Maybe fixed by #2? I'll look into it.

**Comment by johtoblan** [comment] 2020-11-09 20:37
@havardf How is this reproduced?

**Comment by havardf** [comment] 2020-11-10 16:29
> @havardf How is this reproduced?

I think just remove the time.Sleep() call, setup a client that listens for events, and send some events. You should see that many/most events are lost. If all your events are coming through, the issues is gone :)

**Comment by johtoblan** [comment] 2020-11-11 14:04
Seems to be cloudevents use sleep also, we open an issue at theirs to check why.

**Comment by mpejcoch** [comment] 2020-11-11 21:57
https://github.com/cloudevents/sdk-go/issues/608

**Closed** 2020-11-16 17:23 UTC
